#!/bin/csh
#
# This script will create a tar.gz file for each directory 
#
# By: Chris Capobianco
# Date: 02/04/07

# Loop over each sub-directory in current directory
foreach dir_name (*)
  if( -d $dir_name ) then

    # Create tar.gz file for each directory
    tar -cvf $dir_name.tar $dir_name/
    gzip $dir_name.tar
    rm -fr $dir_name

    echo "*** Completed compressing $dir_name ***"
  else
    continue
  endif
end
echo "*** Done ***"

