#!/bin/csh
#
# This script will execute a batch of symba runs
#
# N.B. - Ensure a soft link to symba exists in each directory
#      - Ensure the input file has the name symba.in
#
# By: Chris Capobianco
# Date: 01/27/07

# Loop over each sub-directory in current directory
foreach dir_name (m_025_r16000*)
  if( -d $dir_name ) then
    cd $dir_name

    # Create pl.in files using gen_ray_symba
    ./tools_gen_pl_symba

    # Run simulation using swift_symba5 or swift_symba5_gas
    ./swift_symba5

    # Extract planetary information
    ./follow_symba 2

    # Rename follow_symba output file
    mv follow_2.out ../results/$dir_name.out

    echo "*** Completed the $dir_name run ***"
    cd ../
  else
    continue
  endif
end
#mkdir results
#mv *.out results
echo "*** Done ***"

