#!/bin/csh
#
# This script will unpack each tar file in the directory
#
# By: Chris Capobianco
# Date: 02/04/07

# Loop over each tar file in current directory
foreach tar_name (*.tar)

    # Unpack each tar file
    tar -xvf $tar_name
    rm $tar_name

    echo "*** Completed unpacking $tar_name ***"
end
echo "*** Done ***"

