#!/bin/csh
#
# By: Chris Capobianco
# Date: 01/27/07

# Loop over each file in current directory
foreach file (frame_left*.png)
  echo $file | set file_root=`awk -F"_left" '{print$1}'`
  echo $file | set file_number=`awk -F"_left" '{print$2}'`
  montage -geometry +0+0 $file_root"_left"$file_number $file_root"_right"$file_number $file_root"_"$file_number
  rm $file_root"_left"$file_number $file_root"_right"$file_number
  #echo "*** $file_root ***"
  #echo "*** $file_number ***"
end
echo "*** Done ***"
