#!/bin/csh
#
# This script will create a MPEG movie from a series of PNG files
#
# By: Chris Capobianco
# Date: 01/20/07

# Make a MPEG movie from the sequence of PNG files
echo " *** Make MPEG *** "
convert *.png movie.mpg >& /dev/null

# Remove PNG files
echo " *** Remove PNG *** "
rm *.png

echo " *** Done *** "

#