c100 = read_ascii(template=symba_template)
c800 = read_ascii(template=symba_template)

g100 = read_ascii(template=symba_template)
g800 = read_ascii(template=symba_template)

p100 = read_ascii(template=symba_template)
p800 = read_ascii(template=symba_template)

res = fltarr(6)
myr = 1.0e6

tmp = linfit(g100.t,g100.a)
res[0] = tmp[1]
tmp = linfit(g800.t,g800.a)
res[1] = tmp[1]

tmp = linfit(p100.t[10:85],p100.a[10:85])
res[2] = tmp[1]
tmp = linfit(p800.t[10:80],p800.a[10:80])
res[3] = tmp[1]

tmp = linfit(c100.t,c100.a)
res[4] = tmp[1]
tmp = linfit(c800.t[10:70],c800.a[10:70])
res[5] = tmp[1]

res = res*myr ; AU/Myr

setplot,file='dispersion_migrate.ps'
plot,c800.t/myr,c800.a,xtit='Time (Myr)',ytit='a (AU)',tit='Migration in the Dispersion Dominated Regime',yran=[7.5,11.0],/nodata
oplot,c800.t/myr,c800.a,color=8004
oplot,c100.t/myr,c100.a,color=8004,line=2
oplot,p800.t/myr,p800.a,color=57
oplot,p100.t/myr,p100.a,color=57,line=2
oplot,g800.t/myr,g800.a,color=140
oplot,g100.t/myr,g100.a,color=140,line=2
legend,['Type I - Only; 1 M_Earth; '+strcompress(string(res[0]),/remove_all)+' AU/Myr','Type I - Only; 8 M_Earth; '+strcompress(string(res[1]),/remove_all)+' AU/Myr','Plsmls - Only; 1 M_Earth; '+strcompress(string(res[2]),/remove_all)+' AU/Myr','Plsmls - Only; 8 M_Earth; '+strcompress(string(res[3]),/remove_all)+' AU/Myr','Type I + Plsmls; 1 M_Earth; '+strcompress(string(res[4]),/remove_all)+' AU/Myr','Type I + Plsmls; 8 M_Earth; '+strcompress(string(res[5]),/remove_all)+' AU/Myr'],line=[2,0,2,0,2,0],color=[140,140,57,57,254,254],/right,box=0
setplot,/close

delvar,tmp
