ntype = 3 & nm = n_elements(mass)
titles = ['Gas and Planetesimal', 'Gas Only', 'Planetesimals Only']

; adot vs mass
setplot, file = 'adot_vs_mass.ps', multi=[0, 1, 3]
for j = 0, ntype - 1 do begin & $
  ; index range
  kmin = j*nm & $
  kmax = (j + 1)*nm - 1 & $
  ; plots of adot vs mass
  plot, mass/1.18e-4, migrate[kmin:kmax].a[0], psym = 4, xran = [0, 1.25], yran = [-2.0e-6, 2.0e-6], xtit = 'Mass (M_Earth)', ytit = '<da/dt> (AU/yr)',tit = titles[j] & $
  oploterr, mass/1.18e-4, migrate[kmin:kmax].a[0], migrate[kmin:kmax].a_err[0], 4 & $
  oplot, mass/1.18e-4, fit[0].a[*,j],line = 1 & $
  oplot, mass/1.18e-4, migrate[kmin:kmax].a[1], psym = 5 & $
  oploterr, mass/1.18e-4, migrate[kmin:kmax].a[1], migrate[kmin:kmax].a_err[1], 5 & $
  oplot, mass/1.18e-4, fit[1].a[*,j], line = 2 & $
  legend, ['slope!Llinear!N = ' + strcompress(string(res[0].a[1,j]), /remove_all) + ' AU/yr/M_Earth', 'slope!Lrandom!N = ' + strcompress(string(res[1].a[1,j]), /remove_all) + ' AU/yr/M_Earth'], line = [1, 2], /left, box = 0 & $
endfor
setplot, /close

;setplot, file = 'edot_vs_mass.ps', multi=[0, 1, 3]
;for j = 0, ntype - 1 do begin & $
;  ; index range
;  kmin = j*nm & $
;  kmax = (j + 1)*nm - 1 & $
;  ; plots of edot vs mass
;  plot, mass/1.18e-4, migrate[kmin:kmax].e[0], psym = 4, xran = [0, 1.25], yran = [-2.0e-6, 2.0e-6], xtit = 'Mass (M_Earth)', ytit = '<de/dt> (yr!U-1!N)',tit = titles[j] & $
;  oploterr, mass/1.18e-4, migrate[kmin:kmax].e[0], migrate[kmin:kmax].e_err[0], 4 & $
;  oplot, mass/1.18e-4, fit[0].e[*,j],line = 1 & $
;  oplot, mass/1.18e-4, migrate[kmin:kmax].e[1], psym = 5 & $
;  oploterr, mass/1.18e-4, migrate[kmin:kmax].e[1], migrate[kmin:kmax].e_err[1], 5 & $
;  oplot, mass/1.18e-4, fit[1].e[*,j], line = 2 & $
;  legend, ['m!Llinear!N = ' + strcompress(string(res[0].e[1,j]), /remove_all) + ' yr!U-1!NM_Earth!U-1!N', 'm!Lrandom!N = ' + strcompress(string(res[1].e[1,j]) + ' yr!U-1!NM_Earth!U-1!N', /remove_all)], line = [1, 2], /left, box = 0 & $
;endfor
;setplot, /close

delvar, ntype, nm, j, kmin, kmax, titles
